# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"H_OBC_Kitaev_LR_QP": "01_Hamiltonians.ipynb",
         "H_OBC_Majoranas_Kitaev_LR_QP": "01_Hamiltonians.ipynb",
         "H_APBC_Kitaev_LR_QP": "01_Hamiltonians.ipynb",
         "H_Kitaev_LR_QP": "01_Hamiltonians.ipynb",
         "h_chiral_Kitaev_LR_QP": "01_Hamiltonians.ipynb",
         "H_Kitaev_LR_QP_inf": "01_Hamiltonians.ipynb",
         "h_chiral_Kitaev_LR_QP_inf": "01_Hamiltonians.ipynb",
         "H_pbc_sp": "01_Hamiltonians.ipynb",
         "d_h_chiral_Kitaev_LR_QP_inf": "01_Hamiltonians.ipynb",
         "d_H_pbc_sp": "01_Hamiltonians.ipynb",
         "HLP_d": "01_Hamiltonians.ipynb",
         "d_k_H_Kitaev_LR_QP_inf": "01_Hamiltonians.ipynb",
         "d_phase_H_Kitaev_LR_QP_inf": "01_Hamiltonians.ipynb",
         "Fibonacci": "01_Hamiltonians.ipynb",
         "rot_sigma_y": "01_Hamiltonians.ipynb",
         "f": "01_Hamiltonians.ipynb",
         "df": "01_Hamiltonians.ipynb",
         "HLP": "01_Hamiltonians.ipynb",
         "Fukui_Kitaev_LR_QP_wn": "02_Winding_num.ipynb",
         "Fukui_Kitaev_LR_QP_inf_wn": "02_Winding_num.ipynb",
         "Real_space_Kitaev_LR_QP_wn": "02_Winding_num.ipynb",
         "w": "02_Winding_num.ipynb",
         "Chiral_Kitaev_QP_LR_wn": "02_Winding_num.ipynb",
         "d_num_h_Kitaev_LR_QP_inf": "02_Winding_num.ipynb",
         "Fukui_Kitaev_AA_2D_chern": "02_Winding_num.ipynb",
         "Fukui_Kitaev_AA_2D_chern_inf": "02_Winding_num.ipynb",
         "d_num_k_H_Kitaev_LR_QP": "02_Winding_num.ipynb",
         "d_num_phase_H_Kitaev_LR_QP": "02_Winding_num.ipynb",
         "compute_Kitaev_AA_wn_TKNN": "02_Winding_num.ipynb",
         "d_num_k_H_Kitaev_LR_QP_inf": "02_Winding_num.ipynb",
         "d_num_phase_H_Kitaev_LR_QP_inf": "02_Winding_num.ipynb",
         "compute_Kitaev_AA_wn_TKNN_inf": "02_Winding_num.ipynb"}

modules = ["Hamiltonians.py",
           "Winding_num.py"]

doc_url = "https://jfraxanet.github.io/Topo_LR_Kitaev_AAH/"

git_url = "https://github.com/jfraxanet/Topo_LR_Kitaev_AAH/tree/master/"

def custom_doc_links(name): return None
