# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/04_Localization.ipynb (unless otherwise specified).

__all__ = ['IPR_NPR', 'energy_level_statistics']

# Cell

import numpy as np

# Cell

def IPR_NPR(evec):

    """Calculate NPR and IPR of an evec that is normalized"""

    evec4 = np.abs(evec)**4
    IPR = np.sum(evec4)
    NPR = 1/(np.sum(evec4)*len(evec4))

    return IPR, NPR


def energy_level_statistics(evals):

    '''Compute the energy level statistics of an array of evals'''

    rn = []
    for i in range(len(evals)-2):
        div = min(np.abs(evals[i+1]-evals[i]), np.abs(evals[i+2]-evals[i+1]))/max(np.abs(evals[i+1]-evals[i]), np.abs(evals[i+2]-evals[i+1]))
        rn = np.append(rn, div)

    return rn